//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplomn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставщики
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Поставщики()
        {
            this.Состав_заказа = new HashSet<Состав_заказа>();
        }
    
        public int Код_поставщика { get; set; }
        public string Наименование_поставщика { get; set; }
        public string ИНН { get; set; }
        public string Фамилия_контактного_лица { get; set; }
        public string Имя_контактного_лица { get; set; }
        public string Отчество_контактного_лица { get; set; }
        public string Телефон_контактного_лица { get; set; }
        public string Адрес_поставщика { get; set; }
        public string Email_поставщика { get; set; }
        public byte[] Логотип { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_заказа> Состав_заказа { get; set; }
    }
}
