//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplomn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Состав_заказа
    {
        public int Код_записиСЗ { get; set; }
        public int Код_поставки { get; set; }
        public int Код_товара { get; set; }
        public int Количество { get; set; }
        public decimal Цена_за_ед_покупка { get; set; }
        public int Код_поставщика { get; set; }
    
        public virtual Поставка Поставка { get; set; }
        public virtual Поставщики Поставщики { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
