//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplomn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Состав_продажи
    {
        public int Код_записиСП { get; set; }
        public int Код_чека { get; set; }
        public int Код_товара { get; set; }
        public int Количество { get; set; }
        public decimal Цена { get; set; }
    
        public virtual Продажи Продажи { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
